name: Send Stock Movement Signal

on:
  workflow_dispatch:  # Allows you to trigger manually from GitHub UI

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements1.txt

      - name: Run stock trading signal script
        run: python auxillary/trading.py
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECIEVER: ${{ secrets.EMAIL_RECIEVER }}
      
      - name: Commit and push updated signals_sent_today.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add json_folder/signals_sent_today.json
          git commit -m "Update signals_sent_today.json [bot]" || echo "No changes to commit"
          git push
