name: Webscrape Market Data

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Google Chrome (no Snap)
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get update
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Install matching ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Using Chrome version $CHROME_VERSION"
        DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$CHROME_VERSION")
        wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$DRIVER_VERSION/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Print Chrome + Driver Info
      run: |
          which google-chrome
          google-chrome --version
          which chromedriver
          chromedriver --version

    - name: Kill any stray Chrome processes
      run: |
        pkill chrome || true
        pkill chromedriver || true

    - name: Run scraper
      run: python web_scraper.py
  