name: Webscrape Market Data

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
      
    - name: Install headless Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          fonts-liberation libnss3 libxss1 libasound2 \
          libx11-xcb1 libxcomposite1 libxcursor1 \
          libxdamage1 libxi6 libxtst6 libxrandr2 xdg-utils

    - name: Install Google Chrome (no Snap)
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get update
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Install matching ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Using Chrome version $CHROME_VERSION"
        DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$CHROME_VERSION")
        wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$DRIVER_VERSION/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Print Chrome + Driver Info
      run: |
        which google-chrome
        google-chrome --version
        which chromedriver
        chromedriver --version

    - name: Kill stray Chrome processes and clean temp profiles
      run: |
        pkill chrome || true
        pkill chromedriver || true
        rm -rf /tmp/chrome-profile-* || true

    - name: Run scraper
      run: python web_scraper.py

    - name: Upload fear & greed debug artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fear_greed_debug
        path: |
          fear_greed_debug.png
          page_source.html
